name: 게임바이블 배포스크립트

on:
    pull_request:
        types:
            - closed
        branches:
            - master

jobs:
    if_merged:
        if: github.event.pull_request.merged == true
        runs-on: self-hosted
        steps:
            - name: 머지확인
              run: |

                  echo "PR was merged"
                  pwd
                  cd ./../gamebible-backend/
                  pwd
                  ls -a
                  if [ -d .git ]; then echo ".git directory exists"; else echo ".git directory does not exist"; fi
                  git pull origin master
                  k1ju
                  ${{  secrets.TOKEN  }}
                  sudo pm2 restart 0
